--- #YAML:1.0
name: WWW-Geni
abstract: Perl extension Geni.com
version: 0.2.0
author:
  - Erin Spiceland <erin@thespicelands.com>
license: perl
distribution_type: module
requires:
  ExtUtils::MakeMaker:  0
  HTTP::Cookies: 0
  HTTP::Response: 0
  LWP::UserAgent: 0
  JSON: 0
  perl: 5.005_03
recommends:
build_requires:
  ExtUtils::MakeMaker:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
